In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(f"{arr[::-1]}")

[5 4 3 2 1]


In [2]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

diff = np.subtract(arr1, arr2)

print(f"{diff}")

[[0 0]
 [0 0]]


In [3]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, 3])

most_freq_x = np.argmax(np.bincount(x))
x_i = np.where(x==most_freq_x)
print(f"Freq: {most_freq_x}\nIndices: {x_i}")

most_freq_y = np.argmax(np.bincount(y))
y_i = np.where(y==most_freq_y)
print(f"Freq: {most_freq_y}\nIndices: {y_i}")

Freq: 1
Indices: (array([0, 5, 7, 8, 9]),)
Freq: 3
Indices: (array([ 4,  8,  9, 10]),)


In [4]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

total = np.sum(gfg)
print(total)

total_row = np.sum(gfg, axis=1)
print(total_row)

total_col = np.sum(gfg, axis=0)
print(total_col)

45
[[14]
 [16]
 [15]]
[[20  9 16]]
